"""
Git provider — provider-agnostic PR/MR creation for runbook drafts.

Supported providers (set via GIT_PROVIDER env var):
  github        — GitHub (default)
  gitlab        — GitLab (self-hosted or gitlab.com)
  azure-devops  — Azure DevOps Services or Server

Required environment variables (per provider):
  All providers:
    GIT_PROVIDER         — provider name (default: github)
    GIT_RUNBOOK_REPO     — repo path (format varies per provider, see below)
    GIT_BASE_BRANCH      — base branch (default: main)
    RUNBOOK_PATH_PREFIX  — path prefix inside repo

  github:
    GIT_TOKEN or GITHUB_TOKEN
    GIT_HOST             — GitHub Enterprise host (optional, e.g. github.myco.com)
    GIT_RUNBOOK_REPO     — 'org/repo'

  gitlab:
    GIT_TOKEN or GITLAB_TOKEN
    GIT_HOST             — GitLab host (default: https://gitlab.com)
    GIT_RUNBOOK_REPO     — 'group/repo' or 'group/subgroup/repo'

  azure-devops:
    GIT_TOKEN or AZURE_DEVOPS_TOKEN  — Personal Access Token with Code (Read & Write)
    GIT_HOST             — org URL, e.g. https://dev.azure.com/my-org
    GIT_RUNBOOK_REPO     — 'ProjectName/RepoName'
"""

from __future__ import annotations

import logging
import os
import re
from abc import ABC, abstractmethod
from datetime import date
from typing import Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

GIT_PROVIDER = os.environ.get("GIT_PROVIDER", "github").lower().strip()

RUNBOOK_PATH_PREFIX = os.environ.get(
    "RUNBOOK_PATH_PREFIX",
    "docs/technical-practices/monitoring-observability/runbooks",
)
BASE_BRANCH = os.environ.get("GIT_BASE_BRANCH", os.environ.get("GITHUB_BASE_BRANCH", "main"))
RUNBOOK_REPO = os.environ.get(
    "GIT_RUNBOOK_REPO",
    os.environ.get("GITHUB_RUNBOOK_REPO", "polarpoint-io/markdown-pol-docs"),
)


def _token(env_candidates: list[str]) -> str:
    for name in env_candidates:
        val = os.environ.get(name, "").strip()
        if val:
            return val
    raise RuntimeError(f"No Git token found. Set one of: {', '.join(env_candidates)}")


def _split_repo(repo: str, parts: int = 2, provider: str = "") -> list[str]:
    """Split GIT_RUNBOOK_REPO into parts, raising a clear error on wrong format."""
    pieces = repo.split("/", maxsplit=parts - 1)
    if len(pieces) < parts:
        raise ValueError(
            f"GIT_RUNBOOK_REPO='{repo}' is invalid for {provider}. "
            f"Expected format: {'/'.join(['<part>'] * parts)}"
        )
    return pieces


def _slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_-]+", "-", text)
    return text[:60]


def _pr_body(
    *,
    title: str,
    service: str,
    failure_mode: str,
    source_count: int,
    priority: str,
) -> str:
    return f"""## Runbook Draft — {title}

**Generated by:** [holmesgpt-runbook-mcp](https://github.com/polarpoint-io/holmesgpt-runbook-mcp)
**Priority:** {priority}
**Incidents that triggered this draft:** {source_count}
**Service:** `{service}` | **Failure mode:** `{failure_mode}`

This runbook was drafted automatically from HolmesGPT investigation logs where
`{service}` encountered `{failure_mode}` without a matching runbook in Confluence.

### Before merging

- [ ] Verify diagnosis steps are accurate for your environment
- [ ] Check escalation contacts and channels are current
- [ ] Add cross-links to related runbooks
- [ ] Confirm commands are safe to run in production
- [ ] Change `Status: Draft` → `Status: Approved` in frontmatter
- [ ] Remove `Source: holmesgpt-runbook-mcp` or update to `Source: human-reviewed`

The investigation logs that generated this are in `#holmes-investigations`.
"""


# ---------------------------------------------------------------------------
# Abstract base
# ---------------------------------------------------------------------------

class _GitProvider(ABC):
    @abstractmethod
    def open_pr(
        self,
        *,
        title: str,
        service: str,
        failure_mode: str,
        runbook_markdown: str,
        source_count: int,
        priority: str,
    ) -> dict:
        """
        Create a branch, commit the runbook markdown, and open a draft PR/MR.
        Returns: {pr_url, pr_number, branch_name, file_path}
        """


# ---------------------------------------------------------------------------
# GitHub implementation
# ---------------------------------------------------------------------------

class _GitHubProvider(_GitProvider):
    def __init__(self) -> None:
        from github import Github  # noqa: PLC0415
        token = _token(["GIT_TOKEN", "GITHUB_TOKEN"])
        host = os.environ.get("GIT_HOST", "").strip()
        if host:
            from github import Github as GH, Auth  # noqa: PLC0415
            self._gh = GH(auth=Auth.Token(token), base_url=f"https://{host.rstrip('/')}/api/v3")
        else:
            self._gh = Github(token)

    def open_pr(
        self,
        *,
        title: str,
        service: str,
        failure_mode: str,
        runbook_markdown: str,
        source_count: int,
        priority: str,
    ) -> dict:
        from github import GithubException  # noqa: PLC0415

        repo = self._gh.get_repo(RUNBOOK_REPO)
        today = date.today().isoformat()
        slug = _slugify(f"{service}-{failure_mode}")
        branch_name = f"runbook/auto-{slug}"
        file_path = f"{RUNBOOK_PATH_PREFIX}/rb_{slug}.md"

        final_markdown = runbook_markdown.replace(
            "  Status: Draft",
            f"  Status: Draft\n  Source: holmesgpt-runbook-mcp\n  Generated: {today}\n  Gap-Count: {source_count}",
        )

        # Create branch
        base_sha = repo.get_branch(BASE_BRANCH).commit.sha
        try:
            repo.create_git_ref(f"refs/heads/{branch_name}", base_sha)
        except GithubException as exc:
            if exc.status != 422:
                raise
            logger.info("Branch %s already exists", branch_name)

        # Create or update file
        try:
            existing = repo.get_contents(file_path, ref=branch_name)
            repo.update_file(
                path=file_path,
                message=f"draft(runbook): update {title}",
                content=final_markdown,
                sha=existing.sha,
                branch=branch_name,
            )
        except GithubException:
            repo.create_file(
                path=file_path,
                message=f"draft(runbook): {title} [{source_count} incidents]",
                content=final_markdown,
                branch=branch_name,
            )

        # Open PR (idempotent)
        existing_prs = list(repo.get_pulls(state="open", head=f"{repo.owner.login}:{branch_name}"))
        if existing_prs:
            pr = existing_prs[0]
        else:
            pr = repo.create_pull(
                title=f"[Runbook Draft] {title}",
                body=_pr_body(
                    title=title,
                    service=service,
                    failure_mode=failure_mode,
                    source_count=source_count,
                    priority=priority,
                ),
                head=branch_name,
                base=BASE_BRANCH,
                draft=True,
            )

        return {
            "pr_url": pr.html_url,
            "pr_number": pr.number,
            "branch_name": branch_name,
            "file_path": file_path,
        }


# ---------------------------------------------------------------------------
# GitLab implementation
# ---------------------------------------------------------------------------

class _GitLabProvider(_GitProvider):
    def __init__(self) -> None:
        import gitlab  # noqa: PLC0415
        token = _token(["GIT_TOKEN", "GITLAB_TOKEN"])
        host = os.environ.get("GIT_HOST", "https://gitlab.com").strip()
        self._gl = gitlab.Gitlab(url=host, private_token=token)
        self._gl.auth()

    def open_pr(
        self,
        *,
        title: str,
        service: str,
        failure_mode: str,
        runbook_markdown: str,
        source_count: int,
        priority: str,
    ) -> dict:
        today = date.today().isoformat()
        slug = _slugify(f"{service}-{failure_mode}")
        branch_name = f"runbook/auto-{slug}"
        file_path = f"{RUNBOOK_PATH_PREFIX}/rb_{slug}.md"

        final_markdown = runbook_markdown.replace(
            "  Status: Draft",
            f"  Status: Draft\n  Source: holmesgpt-runbook-mcp\n  Generated: {today}\n  Gap-Count: {source_count}",
        )

        project = self._gl.projects.get(RUNBOOK_REPO)

        # Create branch (idempotent)
        existing_branches = [b.name for b in project.branches.list(search=branch_name)]
        if branch_name not in existing_branches:
            project.branches.create({"branch": branch_name, "ref": BASE_BRANCH})

        # Create or update file
        try:
            f = project.files.get(file_path=file_path, ref=branch_name)
            f.content = final_markdown
            f.encoding = "text"
            f.save(branch=branch_name, commit_message=f"draft(runbook): update {title}")
        except Exception:
            project.files.create({
                "file_path": file_path,
                "branch": branch_name,
                "content": final_markdown,
                "commit_message": f"draft(runbook): {title} [{source_count} incidents]",
            })

        # Open MR (idempotent)
        existing_mrs = project.mergerequests.list(
            state="opened",
            source_branch=branch_name,
            target_branch=BASE_BRANCH,
        )
        if existing_mrs:
            mr = existing_mrs[0]
        else:
            mr = project.mergerequests.create({
                "source_branch": branch_name,
                "target_branch": BASE_BRANCH,
                "title": f"Draft: [Runbook Draft] {title}",
                "description": _pr_body(
                    title=title,
                    service=service,
                    failure_mode=failure_mode,
                    source_count=source_count,
                    priority=priority,
                ),
                "draft": True,
            })

        return {
            "pr_url": mr.web_url,
            "pr_number": mr.iid,
            "branch_name": branch_name,
            "file_path": file_path,
        }


# ---------------------------------------------------------------------------
# Azure DevOps implementation
# ---------------------------------------------------------------------------

class _AzureDevOpsProvider(_GitProvider):
    """
    Creates pull requests via the azure-devops Python SDK.

    GIT_RUNBOOK_REPO format: 'ProjectName/RepoName'
    GIT_HOST format: 'https://dev.azure.com/my-org'
    """

    def __init__(self) -> None:
        from azure.devops.connection import Connection  # noqa: PLC0415
        from msrest.authentication import BasicAuthentication  # noqa: PLC0415

        token = _token(["GIT_TOKEN", "AZURE_DEVOPS_TOKEN"])
        host = os.environ.get("GIT_HOST", "").strip()
        if not host:
            raise RuntimeError(
                "GIT_HOST is required for azure-devops provider. "
                "Set it to e.g. https://dev.azure.com/my-org"
            )

        credentials = BasicAuthentication("", token)
        self._connection = Connection(base_url=host, creds=credentials)
        self._git_client = self._connection.clients.get_git_client()

    def open_pr(
        self,
        *,
        title: str,
        service: str,
        failure_mode: str,
        runbook_markdown: str,
        source_count: int,
        priority: str,
    ) -> dict:
        from azure.devops.v7_1.git.models import (  # noqa: PLC0415
            GitPush,
            GitRefUpdate,
            GitCommit,
            ItemContent,
            GitChange,
            GitPullRequest,
            GitPullRequestCompletionOptions,
        )

        project_name, repo_name = _split_repo(RUNBOOK_REPO, 2, "azure-devops")

        today = date.today().isoformat()
        slug = _slugify(f"{service}-{failure_mode}")
        branch_name = f"runbook/auto-{slug}"
        file_path = f"{RUNBOOK_PATH_PREFIX}/rb_{slug}.md"

        final_markdown = runbook_markdown.replace(
            "  Status: Draft",
            f"  Status: Draft\n  Source: holmesgpt-runbook-mcp\n  Generated: {today}\n  Gap-Count: {source_count}",
        )

        # Get the base branch ref
        refs = self._git_client.get_refs(
            repository_id=repo_name,
            project=project_name,
            filter=f"heads/{BASE_BRANCH}",
        )
        if not refs:
            raise RuntimeError(f"Base branch '{BASE_BRANCH}' not found in {RUNBOOK_REPO}")
        base_sha = refs[0].object_id

        # Check if branch exists; create if not
        existing_refs = self._git_client.get_refs(
            repository_id=repo_name,
            project=project_name,
            filter=f"heads/{branch_name}",
        )

        new_branch_sha = base_sha
        if existing_refs:
            new_branch_sha = existing_refs[0].object_id

        # Push file to branch
        push = GitPush(
            ref_updates=[
                GitRefUpdate(
                    name=f"refs/heads/{branch_name}",
                    old_object_id="0000000000000000000000000000000000000000"
                    if not existing_refs
                    else new_branch_sha,
                    new_object_id=None,  # filled by commit
                )
            ],
            commits=[
                GitCommit(
                    comment=f"draft(runbook): {title} [{source_count} incidents]",
                    changes=[
                        GitChange(
                            change_type=1,  # add
                            item={"path": f"/{file_path}"},
                            new_content=ItemContent(
                                content=final_markdown,
                                content_type=0,  # rawtext
                            ),
                        )
                    ],
                )
            ],
        )

        try:
            self._git_client.create_push(push, repository_id=repo_name, project=project_name)
        except Exception as exc:
            # File already exists — use change_type 2 (edit)
            logger.info("File may already exist, retrying as edit: %s", exc)
            push.commits[0].changes[0].change_type = 2
            push.ref_updates[0].old_object_id = new_branch_sha
            self._git_client.create_push(push, repository_id=repo_name, project=project_name)

        # Check for existing PR
        existing_prs = self._git_client.get_pull_requests(
            repository_id=repo_name,
            project=project_name,
            search_criteria={"sourceRefName": f"refs/heads/{branch_name}", "status": "active"},
        )

        if existing_prs:
            pr = existing_prs[0]
        else:
            pr = self._git_client.create_pull_request(
                git_pull_request_to_create=GitPullRequest(
                    title=f"[Runbook Draft] {title}",
                    description=_pr_body(
                        title=title,
                        service=service,
                        failure_mode=failure_mode,
                        source_count=source_count,
                        priority=priority,
                    ),
                    source_ref_name=f"refs/heads/{branch_name}",
                    target_ref_name=f"refs/heads/{BASE_BRANCH}",
                    is_draft=True,
                ),
                repository_id=repo_name,
                project=project_name,
            )

        host = os.environ.get("GIT_HOST", "").rstrip("/")
        pr_url = f"{host}/{project_name}/_git/{repo_name}/pullrequest/{pr.pull_request_id}"

        return {
            "pr_url": pr_url,
            "pr_number": pr.pull_request_id,
            "branch_name": branch_name,
            "file_path": file_path,
        }


# ---------------------------------------------------------------------------
# Factory + public API
# ---------------------------------------------------------------------------

_provider_instance: Optional[_GitProvider] = None


def _get_provider() -> _GitProvider:
    global _provider_instance
    if _provider_instance is not None:
        return _provider_instance

    if GIT_PROVIDER == "github":
        _provider_instance = _GitHubProvider()
    elif GIT_PROVIDER == "gitlab":
        _provider_instance = _GitLabProvider()
    elif GIT_PROVIDER == "azure-devops":
        _provider_instance = _AzureDevOpsProvider()
    else:
        raise ValueError(
            f"Unknown GIT_PROVIDER '{GIT_PROVIDER}'. Choose: github | gitlab | azure-devops"
        )

    logger.info("Git provider: %s | repo=%s | branch=%s", GIT_PROVIDER, RUNBOOK_REPO, BASE_BRANCH)
    return _provider_instance


def open_runbook_pr(
    *,
    title: str,
    service: str,
    failure_mode: str,
    runbook_markdown: str,
    source_count: int,
    priority: str = "medium",
) -> dict:
    """
    Open a draft pull request / merge request containing the runbook markdown.

    Provider is selected by GIT_PROVIDER env var (github | gitlab).
    Returns: {pr_url, pr_number, branch_name, file_path}
    """
    return _get_provider().open_pr(
        title=title,
        service=service,
        failure_mode=failure_mode,
        runbook_markdown=runbook_markdown,
        source_count=source_count,
        priority=priority,
    )
