"""GitHub client — opens draft PRs for new runbooks."""

from __future__ import annotations

import os
import logging
import re
from datetime import date
from github import Github, GithubException

logger = logging.getLogger(__name__)

GITHUB_TOKEN = os.environ["GITHUB_TOKEN"]
GITHUB_REPO = os.environ.get("GITHUB_RUNBOOK_REPO", "polarpoint-io/markdown-pol-docs")
RUNBOOK_PATH_PREFIX = os.environ.get(
    "RUNBOOK_PATH_PREFIX",
    "docs/technical-practices/monitoring-observability/runbooks",
)
BASE_BRANCH = os.environ.get("GITHUB_BASE_BRANCH", "main")


def _slugify(text: str) -> str:
    """Convert text to a filename-safe slug."""
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_-]+", "-", text)
    return text[:60]


def open_runbook_pr(
    *,
    title: str,
    service: str,
    failure_mode: str,
    runbook_markdown: str,
    source_count: int,
    priority: str = "medium",
) -> dict:
    """
    Open a GitHub pull request containing the drafted runbook markdown.

    The PR is created against BASE_BRANCH with the file placed under
    RUNBOOK_PATH_PREFIX. The PR description includes a checklist for
    the reviewing platform engineer.

    Returns: {pr_url, pr_number, branch_name, file_path}
    """
    g = Github(GITHUB_TOKEN)
    repo = g.get_repo(GITHUB_REPO)

    today = date.today().isoformat()
    slug = _slugify(f"{service}-{failure_mode}")
    branch_name = f"runbook/auto-{slug}"
    file_path = f"{RUNBOOK_PATH_PREFIX}/rb_{slug}.md"

    # Add generation metadata to frontmatter
    final_markdown = runbook_markdown.replace(
        "  Status: Draft",
        f"  Status: Draft\n  Source: holmesgpt-runbook-mcp\n  Generated: {today}\n  Gap-Count: {source_count}",
    )

    # Create branch from base
    base_sha = repo.get_branch(BASE_BRANCH).commit.sha
    try:
        repo.create_git_ref(f"refs/heads/{branch_name}", base_sha)
        logger.info("Created branch %s", branch_name)
    except GithubException as exc:
        if exc.status == 422:
            logger.info("Branch %s already exists, updating file", branch_name)
        else:
            raise

    pr_body = f"""## Runbook Draft — {title}

**Generated by:** [holmesgpt-runbook-mcp](https://github.com/polarpoint-io/holmesgpt-runbook-mcp)
**Priority:** {priority}
**Incidents that triggered this draft:** {source_count}
**Service:** `{service}` | **Failure mode:** `{failure_mode}`

This runbook was drafted automatically from HolmesGPT investigation logs where
`{service}` encountered `{failure_mode}` without a matching runbook in Confluence.

### Before merging

- [ ] Verify diagnosis steps are accurate for your environment
- [ ] Check escalation contacts and channels are current
- [ ] Add cross-links to related runbooks
- [ ] Confirm commands are safe to run in production
- [ ] Change `Status: Draft` → `Status: Approved` in frontmatter
- [ ] Remove `Source: holmesgpt-runbook-mcp` or update to `Source: human-reviewed`

The investigation logs that generated this are in `#holmes-investigations`.
"""

    # Create or update file on branch
    try:
        existing = repo.get_contents(file_path, ref=branch_name)
        repo.update_file(
            path=file_path,
            message=f"draft(runbook): update {title}",
            content=final_markdown,
            sha=existing.sha,
            branch=branch_name,
        )
    except GithubException:
        repo.create_file(
            path=file_path,
            message=f"draft(runbook): {title} [{source_count} incidents]",
            content=final_markdown,
            branch=branch_name,
        )

    # Open PR (idempotent — check if one already exists)
    existing_prs = list(repo.get_pulls(state="open", head=f"{repo.owner.login}:{branch_name}"))
    if existing_prs:
        pr = existing_prs[0]
    else:
        pr = repo.create_pull(
            title=f"[Runbook Draft] {title}",
            body=pr_body,
            head=branch_name,
            base=BASE_BRANCH,
            draft=True,
        )

    return {
        "pr_url": pr.html_url,
        "pr_number": pr.number,
        "branch_name": branch_name,
        "file_path": file_path,
    }
